name: text_summarization_api
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.8.13
  - setuptools=65.6.3
  - sqlite=3.40.1
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
    - altair==4.2.2
    - anyio==3.6.2
    - astroid==2.13.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - autocorrect==2.6.1
    - backports-zoneinfo==0.2.1
    - black==22.12.0
    - blinker==1.5
    - breadability==0.1.20
    - brotli==1.0.9
    - catalogue==2.0.8
    - cffi==1.15.1
    - chardet==5.1.0
    - charset-normalizer==3.0.1
    - colorama==0.4.6
    - configargparse==1.5.3
    - contourpy==1.0.7
    - coverage==7.1.0
    - cycler==0.11.0
    - cymem==2.0.7
    - decorator==5.1.1
    - dill==0.3.6
    - docopt==0.6.2
    - en-core-web-sm==3.3.0
    - entrypoints==0.4
    - exceptiongroup==1.1.0
    - executing==1.2.0
    - fastapi==0.89.1
    - flask==2.2.2
    - flask-basicauth==0.2.0
    - flask-cors==3.0.10
    - fonttools==4.38.0
    - gevent==22.10.2
    - geventhttpclient==2.0.8
    - greenlet==2.0.2
    - h11==0.14.0
    - icecream==2.1.3
    - idna==3.4
    - importlib-metadata==6.0.0
    - iniconfig==2.0.0
    - isort==5.12.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - langdetect==1.0.9
    - lazy-object-proxy==1.9.0
    - locust==2.14.2
    - lxml==4.9.2
    - markdown-it-py==2.1.0
    - markupsafe==2.1.2
    - matplotlib==3.6.3
    - mccabe==0.7.0
    - mdurl==0.1.2
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - nlp-text-cleaner==1.0.11
    - nltk==3.8.1
    - numpy==1.20.3
    - packaging==23.0
    - pandas==1.5.3
    - pathspec==0.11.0
    - pathy==0.10.1
    - pillow==9.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.6.2
    - protobuf==3.20.3
    - pycountry==22.3.5
    - pycparser==2.21
    - pydantic==1.8.2
    - pydeck==0.8.0
    - pygments==2.14.0
    - pylint==2.15.10
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pytest==7.2.1
    - pytest-cov==4.0.0
    - pytextrank==3.2.4
    - python-dateutil==2.8.2
    - python-graphviz==0.20.1
    - pytz==2022.7.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyzmq==25.0.0
    - regex==2022.10.31
    - requests==2.28.2
    - rich==13.3.1
    - roundrobin==0.0.4
    - scipy==1.10.0
    - semver==2.13.0
    - six==1.16.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.5
    - starlette==0.22.0
    - streamlit==1.17.0
    - sumy==0.11.0
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.6
    - toolz==0.12.0
    - tornado==6.2
    - tqdm==4.64.1
    - typer==0.4.2
    - typing-extensions==4.4.0
    - tzdata==2022.7
    - tzlocal==4.2
    - urllib3==1.26.14
    - uvicorn==0.20.0
    - validators==0.20.0
    - wasabi==0.10.1
    - watchdog==2.2.1
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.12.0
    - zope-event==4.6
    - zope-interface==5.5.2
